// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guyasjbhphdhzzynprzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eWFzamJocGhkaHp6eW5wcnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwODA5MDAsImV4cCI6MjA3NjY1NjkwMH0.QhoIOZn8WQHmrJ0u228W1Lr_msDMXvAPIVBvXAT6Y4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});